services:
  # A Docker web service
  - type: web
    name: webdis
    env: docker
    repo: https://github.com/surelle-ha/zitrav2-corona.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 3100
