services:
  - type: web
    name: webdis
    env: docker
    repo: https://github.com/surelle-ha/zitrav2-corona.git
    plan: free
    branch: main
    envVars:
      - key: SERVER_PORT
        value: $SERVER_PORT
      - key: SESSION_SECRET
        value: $SESSION_SECRET
      - key: SECURITY_SALT
        value: $SECURITY_SALT
      - key: JWT_SECRET_KEY
        value: $JWT_SECRET_KEY
      - key: MONGODB_CONF
        value: $MONGODB_CONF
